[package]
name = "train-trouble-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.3"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["parking_lot", "macros", "rt-multi-thread", "sync", "time"] }
