[package]
name = "train-trouble"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
train-trouble-engine = { version = "0.1.0", path = "../train-trouble-engine" }
